http:
  port: "8081"
  
anypoint:
  api:
    id: "20197058"

racedata:
  host: race-data-sapi
  port: "8081"
  protocol: HTTP
  path: /api

  
scorekeeper:
  host: beyond-test.anypointspeedway.com
  port: "443"
  protocol: HTTPS
  path: /scorekeeper-sapi

challenge:
  aiagent:
    speakname:
      minScore: "4"
      timeout: "20"
    question:
      timeout: "30"
    bias:
      minScore: "100"
      timeout: "60"